apiVersion: v1
kind: Service
metadata:
  name: wb-sql
spec:
  selector:
    app: wb-sql
  ports:
    - protocol: TCP
#      你访问的端口
      port: 3308
      targetPort: 3306
#      NodePort的nodePort必须大于30000
      nodePort: 30002
  type: NodePort
  