apiVersion: v1
# 这个指的是 我 k8s 有哪些 volume
#  我 k8s 有什么？？？？
kind: PersistentVolume
metadata:
  name: local-pv-1
spec:
  storageClassName: k8s-storage-1
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/live"

  