apiVersion: v1
kind: Service
metadata:
  name: wb-redis
spec:
  selector:
    app: wb-redis
  ports:
    - protocol: TCP
      port: 6380
#      Redis 默认端口
      targetPort: 6379
      nodePort: 30003
  type: NodePort