apiVersion: apps/v1
kind: Deployment
metadata:
  name: wb-webook
#  specification
spec:
#  副本数量
  replicas: 2
  selector:
    matchLabels:
      app: wb-webook
#      template 描述的是你的 POD 是什么样的
  template:
    metadata:
      labels:
        app: wb-webook
#    POD 的具体信息
    spec:
      containers:
        - name: webook
          image: bolognagene/webook:0.2
          ports:
            - containerPort: 8081
