apiVersion: v1
kind: Service
metadata:
  name: wb-webook
spec:
#  ClusterIP
  type: NodePort
  selector:
    app: wb-webook
  ports:
    - protocol: TCP
      name: http
      port: 8081
      targetPort: 8081
      nodePort: 30004

  